import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SocketProvider } from "@/providers/socket-provider";
import { UserRoomProvider } from "@/providers/user-name-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <SocketProvider>
          <UserRoomProvider>
          {children}
          </UserRoomProvider>
        
        </SocketProvider>
      </body>
    </html>
  );
}
